# Generated by Django 3.1.2 on 2020-11-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('weight', models.FloatField()),
                ('bulk_price', models.IntegerField()),
                ('per_unit_price', models.FloatField()),
                ('curr_price', models.FloatField()),
                ('product_name', models.CharField(max_length=32)),
            ],
        ),
    ]
