# Generated by Django 3.1.2 on 2020-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201120_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SF_name', models.CharField(max_length=32)),
                ('email', models.CharField(default='', max_length=64)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=500)),
                ('password', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
