# Generated by Django 3.1.3 on 2020-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SF_name', models.CharField(max_length=32)),
                ('email', models.CharField(default='', max_length=64)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=500)),
                ('password', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='SF_name',
            new_name='CU_name',
        ),
    ]
