# Generated by Django 3.1.3 on 2020-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201211_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
